Add support for custom strategies
ueman/unleash pull request #11
Opened 2021-04-18 19:23 UTC by cyucelen

Regarding #4

2021-04-19 06:15 UTC, ueman requested changes
Thanks for doing this. I really appreciate it. This just needs a couple small touches and it should be good to go.

Besides the comments I left inline this also needs to send available stategies to the register endpoint.

2021-04-19 06:15 UTC, ueman commented on lib/src/strategy.dart
> +  bool isEnabled(Map<String, dynamic> parameters);
Does `isEnabled` need to support default values?

2021-04-19 06:15 UTC, ueman commented on lib/src/strategies.dart
> +class UnknownStrategy implements ActivationStrategy {
This is a strategy which is used when no better fitting strategy is found, correct? If so shouldn't this take the default value, which gets passed to `unleash.isEnabled("AwesomeFeature", defaultValue: true);`

2021-04-19 06:15 UTC, ueman commented on lib/src/strategy.dart
> +  String name();
This should be a field, not a method.

2021-04-19 06:15 UTC, ueman commented on test/unleash_test.dart
> +    expect(unleash.isEnabled('Demo'), false);
This should still be true not false, it's probably related to the `UnknownStategy` always returning `false`.

2021-04-19 06:15 UTC, ueman commented on lib/src/strategies.dart
> +class UnknownStrategy implements ActivationStrategy {
It probalby should also be called FallbackStategy to better reflect its purpose.

2021-04-19 06:22 UTC, cyucelen commented on test/unleash_test.dart
> +    expect(unleash.isEnabled('Demo'), false);
Actually this not related to `UnknownStrategy`. When you don't use strategies you added on dashboard, it counts as `false`. At least this is the behavior of `go` client.

2021-04-19 06:26 UTC, cyucelen commented on lib/src/strategies.dart
> +class UnknownStrategy implements ActivationStrategy {
When you define multiple strategies for your toggle from dashboard, behavior of client is to check every strategy until find a `true` one. The reason I add `UnknownStrategy` is, always return `false` to check further strategies. 

```dart
    for (final strategy in strategies) {
      final foundStrategy = _activationStrategies.firstWhere(
        (activationStrategy) => activationStrategy.name() == strategy.name,
        orElse: () => UnknownStrategy(),
      );

      final parameters = strategy.parameters ?? <String, dynamic>{};

      if (foundStrategy.isEnabled(parameters)) {
        return true;
      }
    }
    
    return false;
```

2021-04-19 06:31 UTC, ueman commented on lib/src/strategies.dart
> +class UnknownStrategy implements ActivationStrategy {
Ah I see. I didn't know that. Thanks for the clarification.

2021-04-19 06:43 UTC, cyucelen commented on lib/src/strategy.dart
> +  bool isEnabled(Map<String, dynamic> parameters);
I think it is not needed, since we are just evaluating data we have, there should not be any problem. Let's say client is not able to fetch toggles, then there will be no strategies and `defaultValue` which user specified will be used independent of strategies.

2021-04-19 06:59 UTC, cyucelen commented
Thanks for the fast feedback. If it looks good to you, you can resolve current conversations. I will try to take a look at register endpoint behavior you mentioned later today.

2021-04-19 07:03 UTC, cyucelen commented on lib/src/strategies.dart
> +class UnknownStrategy implements ActivationStrategy {
It could be expressed/documented better in term of tests, excuse me for not adding enough test cases for the behavior. I don't have much time to invest these days :/ Maybe I can add more test cases when I find some free time later.

2021-04-21 10:35 UTC, cyucelen commented
I added strategy names to register. I think we are ready to ship. 🚀

2021-04-21 12:25 UTC, ueman commented
Yes, looks good. I'll try to release it later today.

2021-04-21 14:41 UTC, merged